create table if not exists group__item
(
    group_id integer not null,
    items_id integer not null,
    constraint uk_dhg1gs2siwbw3gg5v2jp150p8
    unique (items_id)
    );

create table if not exists users
(
    username varchar(50)  not null,
    password varchar(100) not null,
    enabled  boolean default true,
    id       bigserial,
    constraint users_pk
    primary key (id)
    );

create unique index if not exists users_id_uindex
    on users (id);

create table if not exists authorities
(
    authority varchar(50) not null,
    id        serial,
    constraint authorities_pk
    primary key (id)
    );

create unique index if not exists authorities_id_uindex
    on authorities (id);

create table if not exists configuration
(
    id         integer generated by default as identity,
    resolution varchar(255),
    constraint configuration_pkey
    primary key (id)
    );

create table if not exists group_
(
    id     integer generated by default as identity,
    title  varchar(255),
    parent integer,
    constraint group__pkey
    primary key (id),
    constraint fkokhdio2iuajawc7l6fjt9d3w2
    foreign key (parent) references group_
    );

create table if not exists generactive_item
(
    id         integer not null,
    currency   varchar(255),
    image_url  varchar(255),
    price      integer,
    title      varchar(255),
    parent     integer,
    complexity double precision,
    constraint generactive_item_pkey
    primary key (id),
    constraint fk_591nognq3vsxflb2l9vtdm1yf
    foreign key (parent) references group_
    );

create table if not exists item
(
    id        integer not null,
    currency  varchar(255),
    image_url varchar(255),
    price     integer,
    title     varchar(255),
    parent    integer,
    constraint item_pkey
    primary key (id),
    constraint fk1uuf9xnndtfoxis5g3ro0uvmv
    foreign key (parent) references group_
    );

create table if not exists users_authorities
(
    user_id  bigint not null,
    roles_id bigint not null,
    constraint users_authorities_pkey
    primary key (user_id, roles_id),
    constraint users_authorities_users_id_fk
    foreign key (user_id) references users,
    constraint users_authorities_authorities_id_fk
    foreign key (roles_id) references authorities
    );

