create table if not exists group__group_
(
    group_id  integer not null,
    groups_id integer not null,
    constraint uk_98nsrh630p8gq2rk93vt8qq5t
    unique (groups_id)
    );

create table if not exists group__item
(
    group_id integer not null,
    items_id integer not null,
    constraint uk_dhg1gs2siwbw3gg5v2jp150p8
    unique (items_id)
    );

create table if not exists role_users
(
    role_id  bigint not null,
    users_id bigint not null,
    constraint authorities_users_pkey
    primary key (role_id, users_id)
    );

create table if not exists role
(
    id   bigint generated by default as identity (maxvalue 2147483647),
    role varchar(255),
    constraint authorities_pkey
    primary key (id)
    );

create table if not exists configuration
(
    id         integer generated by default as identity,
    resolution varchar(255),
    constraint configuration_pkey
    primary key (id)
    );

create table if not exists group_
(
    created_by varchar(50),
    created_at date,
    updated_at date,
    id         integer generated by default as identity,
    title      varchar(255),
    parent     integer,
    constraint group__pkey
    primary key (id),
    constraint fkokhdio2iuajawc7l6fjt9d3w2
    foreign key (parent) references group_
    );

create table if not exists generactive_item
(
    createdat  timestamp,
    createdby  varchar(255),
    updatedat  timestamp,
    created_at timestamp,
    created_by varchar(255),
    updated_at timestamp,
    id         integer not null,
    currency   varchar(255),
    image_url  varchar(255),
    price      integer,
    title      varchar(255),
    parent     integer,
    complexity double precision,
    constraint generactive_item_pkey
    primary key (id),
    constraint fk_591nognq3vsxflb2l9vtdm1yf
    foreign key (parent) references group_
    );

create table if not exists item
(
    created_by varchar(50),
    created_at date,
    updated_at date,
    id         integer not null,
    currency   varchar(255),
    image_url  varchar(255),
    price      integer,
    title      varchar(255),
    parent     integer,
    constraint item_pkey
    primary key (id),
    constraint fk1uuf9xnndtfoxis5g3ro0uvmv
    foreign key (parent) references group_
    );

create table if not exists users
(
    id       bigint generated by default as identity (maxvalue 2147483647),
    enabled  boolean default true,
    password varchar(255) not null,
    username varchar(255) not null,
    constraint users_pkey
    primary key (id),
    constraint uk_r43af9ap4edm43mmtq01oddj6
    unique (username)
    );

create table if not exists users_role
(
    role_id bigint not null,
    user_id bigint not null,
    constraint users_authorities_pkey
    primary key (user_id, role_id),
    constraint fkq3lq694rr66e6kpo2h84ad92q
    foreign key (user_id) references users,
    constraint fkjqhpip1k4flmj78msqpi37qdc
    foreign key (role_id) references role
    );

create table if not exists authority
(
    id   serial,
    name varchar(50) not null,
    constraint authority_pk
    primary key (id)
    );

create unique index if not exists authority_id_uindex
    on authority (id);

create table if not exists roles_authority
(
    role_id      integer not null,
    authority_id integer not null,
    constraint roles_authority_pk
    primary key (role_id, authority_id),
    constraint roles_authority_role_id_fk
    foreign key (role_id) references role,
    constraint roles_authority_authority_id_fk
    foreign key (authority_id) references authority
    );

