create table if not exists group__item
(
    group_id integer not null,
    items_id integer not null,
    constraint uk_dhg1gs2siwbw3gg5v2jp150p8
        unique (items_id)
);

create table if not exists users
(
    username varchar(50)  not null,
    password varchar(100) not null,
    enabled  boolean default true,
    constraint users_pkey
        primary key (username)
);

create table if not exists authorities
(
    username  varchar(50) not null,
    authority varchar(50) not null,
    constraint authorities_username_authoritie_key
        unique (username, authority),
    constraint authorities_users_username_fk
        foreign key (username) references users
);

create table if not exists configuration
(
    id         integer generated by default as identity,
    resolution varchar(255),
    constraint configuration_pkey
        primary key (id)
);

create table if not exists group_
(
    id     integer generated by default as identity,
    title  varchar(255),
    parent integer,
    constraint group__pkey
        primary key (id),
    constraint fkokhdio2iuajawc7l6fjt9d3w2
        foreign key (parent) references group_
);

create table if not exists generactive_item
(
    id         integer not null,
    currency   varchar(255),
    image_url  varchar(255),
    price      integer,
    title      varchar(255),
    parent     integer,
    complexity double precision,
    constraint generactive_item_pkey
        primary key (id),
    constraint fk_591nognq3vsxflb2l9vtdm1yf
        foreign key (parent) references group_
);

create table if not exists item
(
    id        integer not null,
    currency  varchar(255),
    image_url varchar(255),
    price     integer,
    title     varchar(255),
    parent    integer,
    constraint item_pkey
        primary key (id),
    constraint fk1uuf9xnndtfoxis5g3ro0uvmv
        foreign key (parent) references group_
);


