create table if not exists configuration
(
    id         serial
        constraint configuration_pkey
            primary key,
    resolution varchar(3)
        constraint configuration_resolution_check
            check ((resolution)::text = ANY
                   ((ARRAY ['HD'::character varying, 'FHD'::character varying, '_4K'::character varying])::text[]))
);

alter table configuration
    owner to postgres;

create table if not exists group_
(
    id     integer generated by default as identity
        constraint group__pkey
            primary key,
    title  varchar(255),
    parent integer
        constraint fkokhdio2iuajawc7l6fjt9d3w2
            references group_
);

alter table group_
    owner to postgres;

create table if not exists generactive_item
(
    id         integer not null
        constraint generactive_item_pkey
            primary key,
    currency   varchar(255),
    image_url  varchar(255),
    price      integer,
    title      varchar(255),
    parent     integer
        constraint fk_591nognq3vsxflb2l9vtdm1yf
            references group_
        constraint generactive_item_group__id_fk
            references group_,
    complexity double precision
);

alter table generactive_item
    owner to postgres;

create table if not exists item
(
    id        integer not null
        constraint item_pkey
            primary key,
    currency  varchar(255),
    image_url varchar(255),
    price     integer,
    title     varchar(255),
    parent    integer
        constraint fk1uuf9xnndtfoxis5g3ro0uvmv
            references group_
);

alter table item
    owner to postgres;

create table if not exists group__group_
(
    group_id  integer not null
        constraint fk4i0e63bgasa0yspqybj613ehw
            references group_,
    groups_id integer not null
        constraint uk_98nsrh630p8gq2rk93vt8qq5t
            unique
        constraint fk58stkgqp8m1x5woycg8e9qg3h
            references group_
);

alter table group__group_
    owner to postgres;

create table if not exists group__item
(
    group_id integer not null
        constraint fk658rdu6vlxlibkkexvf45k4df
            references group_,
    items_id integer not null
        constraint uk_dhg1gs2siwbw3gg5v2jp150p8
            unique
);

alter table group__item
    owner to postgres;