create table if not exists group__group_
(
    group_id  integer not null,
    groups_id integer not null,
    constraint uk_98nsrh630p8gq2rk93vt8qq5t
        unique (groups_id)
);

create table if not exists group__item
(
    group_id integer not null,
    items_id integer not null,
    constraint uk_dhg1gs2siwbw3gg5v2jp150p8
        unique (items_id)
);

create table if not exists configuration
(
    id         integer generated by default as identity,
    resolution varchar(255),
    constraint configuration_pkey
        primary key (id)
);

create table if not exists group_
(
    id     integer generated by default as identity,
    title  varchar(255),
    parent integer,
    constraint group__pkey
        primary key (id),
    constraint fkokhdio2iuajawc7l6fjt9d3w2
        foreign key (parent) references group_
);

create table if not exists generactive_item
(
    id         integer not null,
    currency   varchar(255),
    image_url  varchar(255),
    price      integer,
    title      varchar(255),
    parent     integer,
    complexity double precision,
    constraint generactive_item_pkey
        primary key (id),
    constraint fk_591nognq3vsxflb2l9vtdm1yf
        foreign key (parent) references group_
);

create table if not exists item
(
    id        integer not null,
    currency  varchar(255),
    image_url varchar(255),
    price     integer,
    title     varchar(255),
    parent    integer,
    constraint item_pkey
        primary key (id),
    constraint fk1uuf9xnndtfoxis5g3ro0uvmv
        foreign key (parent) references group_
);

create table if not exists users
(
    username varchar(50)  not null,
    password varchar(100) not null,
    enabled  boolean default true,
    id       serial,
    constraint users_pkey
        primary key (username)
);

create unique index if not exists users_id_uindex
    on users (id);

create table if not exists authorities
(
    username  varchar(50) not null,
    authority varchar(50) not null,
    id        serial,
    constraint authorities_pk
        primary key (id),
    constraint authorities_username_authoritie_key
        unique (username, authority),
    constraint authorities_users_username_fk
        foreign key (username) references users
);

create table if not exists users_authorities
(
    user_id       bigint       not null,
    roles_id      bigint       not null,
    user_username varchar(255) not null,
    constraint users_authorities_pkey
        primary key (user_id, roles_id),
    constraint uk_tloe6d1emhvo3hum12hr82wx3
        unique (roles_id),
    constraint fk1x2ox3q5mx77gsvu79j3yk83s
        foreign key (user_username) references users
);

